"""Step definitions for FR-006: No-change commit guard."""

import pathlib
import tempfile

from behave import given, then, when

import src.pipeline_feed


def _minimal_article(published: str) -> src.pipeline_feed.Article:
    """Return a single Article with all required fields set; published equals updated."""
    return src.pipeline_feed.Article(
        title="Test Article",
        authors=["Test Author"],
        primary_category="cs.AI",
        abstract_url="https://arxiv.org/abs/0000.00000v1",
        published=published,
        updated=published,
        abstract="",
        comment=None,
        comment_urls=["https://example.com/"],
    )


def _build_feed_bytes(articles: list[src.pipeline_feed.Article]) -> bytes:
    """Serialize articles to Atom XML via src.pipeline_feed.build_feed."""
    return src.pipeline_feed.build_feed(
        articles,
        category_id="cs.AI",
        strict_mode=False,
        github_repository="owner/code-available-feed",
    )


def _build_minimal_atom_feed() -> bytes:
    """Return Atom XML bytes for a single-entry minimal feed used by commit-guard tests."""
    return _build_feed_bytes([_minimal_article("2026-05-14T15:00:00Z")])


def _build_feed_for_message(n: int, newest_published: str) -> bytes:
    """
    Return Atom XML bytes with n entries.

    The first article carries newest_published (and equal updated); any
    additional articles carry the static "2026-01-01T00:00:00Z" date.  build_feed
    sorts by published descending, so the first article stays at the top of
    the serialized output and build_commit_message_from_bytes reads it as
    the newest entry.

    Parameters:
      n:                number of entries to include
      newest_published: RFC 3339 date string for the newest entry
    """
    articles = [_minimal_article(newest_published)]
    articles.extend(
        _minimal_article("2026-01-01T00:00:00Z") for _ in range(1, n)
    )
    return _build_feed_bytes(articles)


@given('an existing "{filepath}" file with known content')
def step_existing_file_with_known_content(context, filepath):
    """
    Create a fresh temporary run directory, write a known Atom feed at
    filepath, and store the bytes in context.prior_bytes.
    """
    context.run_dir = pathlib.Path(tempfile.mkdtemp())
    full_path = context.run_dir / filepath
    full_path.parent.mkdir(parents=True, exist_ok=True)
    known_bytes = _build_minimal_atom_feed()
    full_path.write_bytes(known_bytes)
    context.prior_bytes = known_bytes


@given("a freshly generated atom.xml with byte-for-byte identical content")
def step_generated_identical(context):
    """Set generated bytes equal to the prior bytes."""
    context.generated_bytes = context.prior_bytes


@given("a freshly generated atom.xml that differs from the existing file by one byte")
def step_generated_differs_by_one_byte(context):
    """Flip the last byte of the prior content to produce a single-byte difference."""
    data = bytearray(context.prior_bytes)
    data[-1] ^= 1
    context.generated_bytes = bytes(data)


@given("a freshly generated atom.xml has been written to that path")
def step_generated_written_to_that_path(context):
    """
    Generate a minimal feed and store its bytes in context.generated_bytes.

    Sets context.prior_bytes to None when the previous Given step did not
    set it (i.e. when the reused FR-001 step for "no file exists" ran, which
    creates a run_dir but does not set prior_bytes).
    """
    if not hasattr(context, "prior_bytes"):
        context.prior_bytes = None
    context.generated_bytes = _build_minimal_atom_feed()


@when("the commit-guard step compares the two files")
@when("the commit-guard step runs")
def step_run_commit_guard(context):
    """Compare prior_bytes with generated_bytes and record the decision."""
    identical = (
        context.prior_bytes is not None
        and context.prior_bytes == context.generated_bytes
    )
    context.guard_result = "no change" if identical else "changed"


@then('the commit-guard step reports "{expected}"')
def step_commit_guard_reports(context, expected):
    """Assert that the guard decision matches expected."""
    assert context.guard_result == expected, (
        f"Expected commit guard result {expected!r}, got {context.guard_result!r}"
    )


@given('an atom.xml containing {count:d} entry whose newest published date is "{published}"')
@given('an atom.xml containing {count:d} entries whose newest published date is "{published}"')
def step_atom_xml_with_entries(context, count, published):
    """Build an Atom feed with count entries; the first entry has the given published date."""
    context.message_feed_bytes = _build_feed_for_message(count, published)


@when("the commit message is constructed from the atom.xml")
def step_construct_commit_message(context):
    """Call build_commit_message_from_bytes and store the result."""
    context.commit_message = src.pipeline_feed.build_commit_message_from_bytes(
        context.message_feed_bytes
    )


@then('the commit message is "{expected}"')
def step_commit_message_is(context, expected):
    """Assert that the constructed commit message matches expected exactly."""
    assert context.commit_message == expected, (
        f"Expected commit message {expected!r}, got {context.commit_message!r}"
    )
