"""Step definitions for FR-006: No-change commit guard."""

import io
import pathlib
import tempfile
import xml.etree.ElementTree as ET

from behave import given, then, when

import src.commit_message
import src.pipeline_feed

_ATOM_NS = "http://www.w3.org/2005/Atom"

# Register the default namespace so the serialiser writes <feed xmlns="...">
# rather than <ns0:feed xmlns:ns0="...">.
ET.register_namespace("", _ATOM_NS)


def _build_minimal_atom_feed() -> bytes:
    """Return minimal Atom XML bytes with one entry, for commit-guard tests."""
    root = ET.Element(f"{{{_ATOM_NS}}}feed")
    entry = ET.SubElement(root, f"{{{_ATOM_NS}}}entry")
    ET.SubElement(entry, f"{{{_ATOM_NS}}}published").text = "2026-05-14T15:00:00Z"
    buf = io.BytesIO()
    ET.ElementTree(root).write(buf, encoding="UTF-8", xml_declaration=True)
    return buf.getvalue()


def _build_feed_for_message(n: int, newest_published: str) -> bytes:
    """
    Return Atom XML bytes with n entries.

    The first entry carries newest_published; additional entries carry an
    earlier placeholder date so newest_published_date_from_feed returns the
    correct maximum.

    Parameters:
      n:                number of entries to include
      newest_published: RFC 3339 date string for the newest entry
    """
    root = ET.Element(f"{{{_ATOM_NS}}}feed")
    entry = ET.SubElement(root, f"{{{_ATOM_NS}}}entry")
    ET.SubElement(entry, f"{{{_ATOM_NS}}}published").text = newest_published
    for _ in range(1, n):
        extra = ET.SubElement(root, f"{{{_ATOM_NS}}}entry")
        ET.SubElement(extra, f"{{{_ATOM_NS}}}published").text = "2026-01-01T00:00:00Z"
    buf = io.BytesIO()
    ET.ElementTree(root).write(buf, encoding="UTF-8", xml_declaration=True)
    return buf.getvalue()


# ---------------------------------------------------------------------------
# Commit-guard scenarios (scenarios 1-3)
# ---------------------------------------------------------------------------


@given('an existing "{filepath}" file with known content')
def step_existing_file_with_known_content(context, filepath):
    """
    Create a fresh temporary run directory, write a known Atom feed at
    filepath, and store the bytes in context.committed_bytes.
    """
    context.run_dir = pathlib.Path(tempfile.mkdtemp())
    full_path = context.run_dir / filepath
    full_path.parent.mkdir(parents=True, exist_ok=True)
    known_bytes = _build_minimal_atom_feed()
    full_path.write_bytes(known_bytes)
    context.committed_bytes = known_bytes


@given("a freshly generated atom.xml with byte-for-byte identical content")
def step_generated_identical(context):
    """Set generated bytes equal to the committed bytes."""
    context.generated_bytes = context.committed_bytes


@given("a freshly generated atom.xml that differs from the existing file by one byte")
def step_generated_differs_by_one_byte(context):
    """Flip the last byte of the committed content to produce a single-byte difference."""
    data = bytearray(context.committed_bytes)
    data[-1] ^= 1
    context.generated_bytes = bytes(data)


@given("a freshly generated atom.xml has been written to that path")
def step_generated_written_to_that_path(context):
    """
    Generate a minimal feed and store its bytes in context.generated_bytes.

    Sets context.committed_bytes to None when the previous Given step did not
    set it (i.e. when the reused FR-001 step for "no file exists" ran, which
    creates a run_dir but does not set committed_bytes).
    """
    if not hasattr(context, "committed_bytes"):
        context.committed_bytes = None
    context.generated_bytes = _build_minimal_atom_feed()


@when("the commit-guard step compares the two files")
@when("the commit-guard step runs")
def step_run_commit_guard(context):
    """Compare committed_bytes with generated_bytes and record the decision."""
    identical = src.pipeline_feed.feeds_are_identical(
        context.committed_bytes, context.generated_bytes
    )
    context.guard_result = "no change" if identical else "changed"


@then('the commit-guard step reports "{expected}"')
def step_commit_guard_reports(context, expected):
    """Assert that the guard decision matches expected."""
    assert context.guard_result == expected, (
        f"Expected commit guard result {expected!r}, got {context.guard_result!r}"
    )


# ---------------------------------------------------------------------------
# Commit message scenarios (scenarios 4-6)
# ---------------------------------------------------------------------------


@given(
    'an atom.xml containing {count:d} {entries_word} whose newest published'
    ' date is "{published}"'
)
def step_atom_xml_with_entries(context, count, entries_word, published):
    """
    Build an Atom feed with count entries; the first entry has the given
    published date.  entries_word ("entry" or "entries") is accepted but
    ignored — the count drives entry generation.
    """
    context.message_feed_bytes = _build_feed_for_message(count, published)


@when("the commit message is constructed from the atom.xml")
def step_construct_commit_message(context):
    """Call build_commit_message_from_bytes and store the result."""
    context.commit_message = src.commit_message.build_commit_message_from_bytes(
        context.message_feed_bytes
    )


@then('the commit message is "{expected}"')
def step_commit_message_is(context, expected):
    """Assert that the constructed commit message matches expected exactly."""
    assert context.commit_message == expected, (
        f"Expected commit message {expected!r}, got {context.commit_message!r}"
    )
