name: pipeline_artifacts

on:
  schedule:
    - cron: '0 06 * * *' # Daily at 06:00 UTC
  workflow_dispatch:

permissions:
  contents: read
  actions: write

jobs:
  pipeline:
    runs-on: ubuntu-24.04
    steps:
      - name: checkout repo
        uses: actions/checkout@v6

      - name: print system info
        run: |
          set -eo pipefail
          docker info
          docker image ls
          docker ps
          df -h
          id

      - name: docker compose build
        run: |
          set -eo pipefail
          export BUILDKIT_PROGRESS=plain
          docker compose build --build-arg UID=$(id -u) --build-arg GID=$(id -g)

      - name: bash scripts/pipeline_artifacts.sh
        run: |
          set -eo pipefail
          bash scripts/pipeline_artifacts.sh

      - name: debug
        if: failure()
        run: |
          docker ps -a | grep -v CONTAINER | cut -d' ' -f1 | xargs -I{} -r bash -c "docker container stats --no-stream {} ; docker logs {}"
